# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('ECOM', 'ECOM'), ('IoT', 'IoT'), ('DBMS', 'DBMS'), ('CMS', 'CMS'), ('Education', 'Education'), ('Artificial Intelligence', 'Artificial Intelligence'), ('NoSQL', 'NoSQL')], default='DBMS', max_length=32, verbose_name='Type'),
        ),
    ]
