# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='LatestReleaseDate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='database',
            field=models.ManyToManyField(blank=True, to='applications.Database'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ManyToManyField(blank=True, to='applications.ProgramLanguage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.ManyToManyField(blank=True, to='applications.Platform'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('NoSQL', 'NoSQL'), ('IoT', 'IoT'), ('Education', 'Education'), ('Artificial Intelligence', 'Artificial Intelligence'), ('DBMS', 'DBMS'), ('ECOM', 'ECOM'), ('CMS', 'CMS')], default='DBMS', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status'),
        ),
    ]
