# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20161205_1454'),
        ('applications', '0002_auto_20161204_2125'),
    ]

    operations = [
    ]
