# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='FirstReleaseDate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DBMS', 'DBMS'), ('HealthCare', 'HealthCare'), ('Artificial Intelligence', 'Artificial Intelligence'), ('IoT', 'IoT'), ('ECOM', 'ECOM'), ('NoSQL', 'NoSQL'), ('Education', 'Education'), ('CMS', 'CMS')], default='DBMS', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending', max_length=32, verbose_name='Status'),
        ),
    ]
