# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
