# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('ctype', models.IntegerField(default=6)),
                ('value', models.CharField(max_length=200)),
                ('xf_index', models.IntegerField(null=True)),
                ('bgx', models.IntegerField(default=64)),
            ],
        ),
        migrations.CreateModel(
            name='Colinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=12)),
                ('xf_index', models.IntegerField(default=-1)),
                ('hidden', models.IntegerField(default=0)),
                ('bit1_flag', models.IntegerField(default=1)),
                ('outline_level', models.IntegerField(default=0)),
                ('collapsed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ColourMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('colour', models.ManyToManyField(to='excel.Colour')),
            ],
        ),
        migrations.CreateModel(
            name='crange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rlo', models.IntegerField(default=0)),
                ('rhi', models.IntegerField(default=0)),
                ('clo', models.IntegerField(default=0)),
                ('chi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_key', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('format_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowStartIndex', models.IntegerField(default=0)),
                ('rowEndIndex', models.IntegerField(default=0)),
                ('colStartIndex', models.IntegerField(default=0)),
                ('colEndIndex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rowinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=345)),
                ('has_default_height', models.IntegerField(default=0)),
                ('outline_level', models.IntegerField(default=0)),
                ('outline_group_starts_ends', models.IntegerField(default=0)),
                ('hidden', models.IntegerField(default=0)),
                ('height_mismatch', models.IntegerField(default=1)),
                ('has_default_xf_index', models.IntegerField(default=0)),
                ('xf_index', models.IntegerField(default=-1)),
                ('additional_space_above', models.IntegerField(default=0)),
                ('additional_space_below', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(default=0)),
                ('sheetName', models.CharField(max_length=200)),
                ('nrows', models.IntegerField(default=0)),
                ('ncols', models.IntegerField(default=0)),
                ('rowinfo_map', models.ManyToManyField(to='excel.Rowinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('codepage', models.IntegerField(null=True)),
                ('countries', models.CharField(max_length=10)),
                ('encoding', models.CharField(max_length=10, null=True)),
                ('nsheets', models.IntegerField(default=0)),
                ('use_mmap', models.IntegerField(default=0)),
                ('formatting_info', models.IntegerField(default=0)),
                ('on_demand', models.IntegerField(default=0)),
                ('ragged_rows', models.IntegerField(default=0)),
                ('colourMap', models.ManyToManyField(to='excel.ColourMap')),
                ('fmtlist', models.ManyToManyField(to='excel.Format')),
            ],
        ),
        migrations.CreateModel(
            name='XF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_style', models.IntegerField(default=0)),
                ('parent_style_index', models.IntegerField(default=0)),
                ('_format_flag', models.IntegerField(default=0)),
                ('_font_flag', models.IntegerField(default=0)),
                ('_alignment_flag', models.IntegerField(default=0)),
                ('_border_flag', models.IntegerField(default=0)),
                ('_background_flag', models.IntegerField(default=0)),
                ('_protection_flag', models.IntegerField(default=0)),
                ('xf_index', models.IntegerField(default=0)),
                ('font_index', models.IntegerField(default=0)),
                ('format_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XFAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_align', models.IntegerField(default=0)),
                ('vert_align', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('text_wrapped', models.IntegerField(default=0)),
                ('indent_level', models.IntegerField(default=0)),
                ('shrink_to_fit', models.IntegerField(default=0)),
                ('text_direction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XFBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_pattern', models.IntegerField(default=0)),
                ('background_colour_index', models.IntegerField(default=0)),
                ('pattern_colour_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XFBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_colour_index', models.IntegerField(default=0)),
                ('bottom_colour_index', models.IntegerField(default=0)),
                ('left_colour_index', models.IntegerField(default=0)),
                ('right_colour_index', models.IntegerField(default=0)),
                ('diag_colour_index', models.IntegerField(default=0)),
                ('top_line_style', models.IntegerField(default=0)),
                ('bottom_line_style', models.IntegerField(default=0)),
                ('left_line_style', models.IntegerField(default=0)),
                ('right_line_style', models.IntegerField(default=0)),
                ('diag_line_style', models.IntegerField(default=0)),
                ('diag_down', models.IntegerField(default=0)),
                ('diag_up', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XFProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_locked', models.IntegerField(default=0)),
                ('formula_hidden', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='xf',
            name='alignment',
            field=models.ManyToManyField(to='excel.XFAlignment'),
        ),
        migrations.AddField(
            model_name='xf',
            name='background',
            field=models.ManyToManyField(to='excel.XFBackground'),
        ),
        migrations.AddField(
            model_name='xf',
            name='border',
            field=models.ManyToManyField(to='excel.XFBorder'),
        ),
        migrations.AddField(
            model_name='xf',
            name='protection',
            field=models.ManyToManyField(to='excel.XFProtection'),
        ),
        migrations.AddField(
            model_name='workbook',
            name='xflist',
            field=models.ManyToManyField(to='excel.XF'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='workBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.WorkBook'),
        ),
        migrations.AddField(
            model_name='merge',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Sheet'),
        ),
        migrations.AddField(
            model_name='crange',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Sheet'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.Rowinfo'),
        ),
    ]
