# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_permission_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('views_student_list', 'get information'), ('views_student_info', 'get detail')), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permission'},
        ),
    ]
