# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_permission_per_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='createTime'),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='updateTime'),
        ),
    ]
