# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
    ]
