# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConsole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('username', models.CharField(max_length=256, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('software_version', models.CharField(blank=True, max_length=256, null=True, verbose_name='SoftwareVersion')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
                ('created_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='CreatedBy')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='CreatedDate')),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='UpdatedBy')),
            ],
            options={
                'verbose_name': 'CloudConsole',
                'verbose_name_plural': 'CloudConsole',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('no_of_servers', models.IntegerField(blank=True, null=True, verbose_name='NoOfServers')),
                ('CPUCores', models.IntegerField(blank=True, null=True, verbose_name='CPUCores')),
                ('memory', models.IntegerField(blank=True, choices=[(8, '8GB'), (2, '2GB'), (4, '4GB')], default=2, null=True, verbose_name='Memory')),
                ('primary_disk', models.IntegerField(blank=True, null=True, verbose_name='PrimaryDisk')),
                ('secondary_disk', models.IntegerField(blank=True, null=True, verbose_name='SecondaryDisk')),
                ('third_disk', models.IntegerField(blank=True, null=True, verbose_name='ThirdDisk')),
                ('band_width', models.IntegerField(blank=True, null=True, verbose_name='Bandwidth')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fraud', 'Fraud'), ('Suspended', 'Suspended'), ('Active', 'Active'), ('Canceled', 'Canceled')], default='Pending', max_length=32, verbose_name='Status')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comment')),
                ('server_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='ServerName')),
                ('password', models.CharField(default='123456', max_length=256, verbose_name='Password')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
                ('created_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='CreatedBy')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='UpdatedDate')),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='UpdatedBy')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], default='Linux', max_length=32, verbose_name='Type')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('AWSPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='AWSPrice')),
                ('AzurePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='AzurePrice')),
                ('GooglePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='GooglePrice')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
                ('created_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='CreatedBy')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='CreatedDate')),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='UpdatedBy')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('instance_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='InstanceID')),
                ('IP', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('CPUCores', models.IntegerField(blank=True, null=True, verbose_name='CPUCores')),
                ('memory', models.IntegerField(blank=True, null=True, verbose_name='Memory')),
                ('primary_disk', models.IntegerField(blank=True, null=True, verbose_name='PrimaryDisk')),
                ('secondary_disk', models.IntegerField(blank=True, null=True, verbose_name='SecondaryDisk')),
                ('third_disk', models.IntegerField(blank=True, null=True, verbose_name='ThirdDisk')),
                ('band_width', models.IntegerField(blank=True, null=True, verbose_name='Bandwidth')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Pending', 'Pending')], default='Pending', max_length=32, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='CreatedDate')),
                ('created_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='CreatedBy')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='CreatedDate')),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='UpdatedBy')),
                ('console_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc', to='packages.CloudConsole')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='packages.Package')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Server',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppid', to='packages.Plan'),
        ),
        migrations.AddField(
            model_name='package',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='applications.Product'),
        ),
        migrations.AddField(
            model_name='package',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pu', to=settings.AUTH_USER_MODEL),
        ),
    ]
