# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='memory',
            field=models.IntegerField(blank=True, choices=[(2, '2GB'), (4, '4GB'), (8, '8GB')], default=2, null=True, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Fraud', 'Fraud'), ('Canceled', 'Canceled'), ('Suspended', 'Suspended')], default='Pending', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], default='Linux', max_length=32, verbose_name='Type'),
        ),
    ]
