# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': '文章', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='author',
            name='company',
            field=models.CharField(max_length=50, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='author',
            name='work',
            field=models.CharField(max_length=20, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_clicknum',
            field=models.IntegerField(null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_imgurl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_ismarkdown',
            field=models.BooleanField(default=False, verbose_name='是否MD格式'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_like',
            field=models.IntegerField(null=True, verbose_name='喜欢数'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_type',
            field=models.CharField(choices=[('Txt', '文本'), ('Link', '链接'), ('Photo', '图片'), ('Blend', '图文')], default='Txt', max_length=50, verbose_name='正文类型'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Classification', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='subTitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='子标题'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 2, 17, 30, 820081, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(default='随笔', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, verbose_name='标签'),
        ),
    ]
